-- V12: Create roles table and user_roles join table for role-based authorization

-- =====================================================
-- CREATE ROLES TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_role_name (name)
);

-- =====================================================
-- CREATE USER_ROLES JOIN TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    INDEX idx_user_roles_user (user_id),
    INDEX idx_user_roles_role (role_id)
);

-- =====================================================
-- INSERT DEFAULT ROLES
-- =====================================================
INSERT INTO roles (name) VALUES
('ROLE_CUSTOMER'),
('ROLE_ADMIN');

-- =====================================================
-- ASSIGN ROLES TO EXISTING USERS
-- =====================================================

-- Assign ROLE_CUSTOMER to all existing users by default
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE r.name = 'ROLE_CUSTOMER';

-- Make specific users admin (e.g., first user and emily.johnson for testing)
INSERT IGNORE INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE r.name = 'ROLE_ADMIN'
AND u.email IN ('admin@example.com', 'emily.johnson@email.com');

-- =====================================================
-- CREATE AN ADMIN USER IF NOT EXISTS
-- =====================================================
-- Password: admin123 (BCrypt hash generated by Spring Security)
INSERT IGNORE INTO users (name, email, password) VALUES
('System Admin', 'admin@example.com', '$2a$10$qIAQzz6kBzTPV/ClEdMcceJQJsybEAqD6pyGe79Vx22kL42OPiBNe');

-- Assign both CUSTOMER and ADMIN roles to the admin user
INSERT IGNORE INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE u.email = 'admin@example.com' AND r.name = 'ROLE_ADMIN';

INSERT IGNORE INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE u.email = 'admin@example.com' AND r.name = 'ROLE_CUSTOMER';

